name: update_upgrade_image

on:
  push:
    branches:
      - master

env:
    PYCURL_SSL_LIBRARY: gnutls

jobs:
  codechecks:
    name: Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout satellite6-upgrade
        uses: actions/checkout@v3

      - name: Set Up Python-${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
            sudo apt-get update --fix-missing
            sudo apt-get install -y libgnutls28-dev libcurl4-openssl-dev libssl-dev
            pip install -r requirements.txt -r requirements-optional.txt
            for config in conf/*.yaml.template; do mv -- "$config" "${config%.template}"; done

      - name: Pre Commit Checks
        uses: pre-commit/action@v3.0.0

      - name: Upgrade Test Coverage (Existence Test)
        run: py.test --cov=upgrade_tests/helpers upgrade_tests/helpers/coverme.py

      - name: Make Docs
        run: |
          make test-docstrings
          make docs

  upgrade_container:
    needs: codechecks
    name: Update Upgrade Container image on Quay.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get image tag
        id: image_tag
        run: |
          echo -n ::set-output name=IMAGE_TAG::
          TAG="${GITHUB_REF##*/}"
          if [ "${TAG}" == "master" ]; then
              TAG="latest"
          fi
          echo "${TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.QUAY_SERVER }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push image to Quay
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.QUAY_SERVER }}/${{ secrets.QUAY_NAMESPACE }}/upgrade:${{ steps.image_tag.outputs.IMAGE_TAG }}
